### ISSUE TITLE
Restructure the content of the learning materials (basic HTML part)

### ISSUE THREAD

**Issue by verpixelt** [cssconf/CSSclasses--old#10]
I would like to propose a different or maybe just a bit more structured order for the part: "Basic HTML & HTML boilerplate (as simple as possible)" as follows:
- Structure of a HTML document
  - doctype
  - html
  - head
    - title
    - meta (charset)
  - body
- Elements
  - Headings (h1-h6)
  - paragraph
  - strong, em
  - break
- Lists
  - Unordered list (ul)
  - Ordered list (ol)
  - Definition list (dl)

I think this would provided every attendee with the elements they need to get started in writing their own content in HTML(e.g. a little todo list with a heading, description and the list itself(yeah yeah I know the damn good 'ol todo list thing ;P)).

**Comment by bastianalbers** [comment]
Lisa and i just discussed a little and kind of lean towards explaining the div tag but maybe leave out the lists. Lists are so confusing styling-wise with the paddings and margins and list style...

**Comment by verpixelt** [comment]
I'm not sure with that. What's the goal of this beginner workshop? Learning HTML and CSS basics I thought. Lists are used that often and are definitely base stuff (okay, maybe the definition list is a bit over the top).

**Comment by Kriesse** [comment]
We opted to explain as litte HTML as possible and fast-track attendees to be able to apply styles as quickly as possible. Goal ist not so much: _Build your valid, semantic website_ but more _have fun with colors, fonts, shapes…_ That's why we explain only very few simple elements.

I agree lists are base stuff, but in my experience total beginners waste at least one hour to understand the nesting of lists (why can't <li> stand alone? etc.). So I would not put it in the tutorial, but definitely explain it one-on-one if someone is obviously more advanced and is trying to create a list. 
@verpixelt sounds ok?
