### ISSUE TITLE
Write paragraph on landing page: "What is CSSclasses"

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#14]
Explain the two-part event: a) workshop, b) hackathon + demos

**Comment by thatbettina** [comment]
How to organize advanced people: 
- postits of topics on the wall for everyone like Learners' Group
- Write on name tag of name and learning topic
- Bar camp style time slots for advanced topics, esp for live coding sessions with FAQs, so that coaches can still coach beginners who are not interested in the topic

Organize tables around interests for beginners and advanced learners

**Comment by maxfell** [comment]
> CSSClasses is a one day event for people who are interested in learning how they can create and manipulate elements on a website. A group of experienced developers will be by your side all day and make sure you return home with a lot of new knowledge.
> The event itself is seperated into two parts: A workshop where you will learn how to get creative with CSS and a hackathon where you can then make your hands dirty and work on your own little fun project.

On the go right now, I will add and push this later today.

**Comment by bastianalbers** [comment]
Merged, looks good!
