### ISSUE TITLE
Add tutorial on transform

### ISSUE THREAD

**Issue by lislis** [cssconf/CSSclasses--old#73]
a little intro so they can manage the challenge

**Comment by bastianalbers** [comment]
Yeah, the planets challenge is super hard because we don't get into transforms or positioning at all before, so you'll have to read up a lot before being able to do it. A little primer on transforms would help a lot... but what to explain here, we didn't know... translate seems weird without positioning, maybe some things like scale or rotate?

**Comment by bastianalbers** [comment]
Should be closed with https://github.com/cssconf/CSSclasses/pull/82

**Comment by Kriesse** [comment]
reviewed and proofread :+1:
